name : Three environemnt setup

# allow this workflow to run manually
-on : workflow_dispatch
jobs:
  
  DevJob:
    runs-on: ubuntu-latest
    environemt: Dev
    steps:
      -name: echo env
      run: running from dev environment
      
   
    QaJob:
    runs-on: ubuntu-latest
    environemt: Qa
    needs: Dev
    steps:
      -name: echo env
      run: running from qa environment
      
      
    PrdJob:
    runs-on: ubuntu-latest
    environemt: Prd
    needs: Qa
    steps:
      -name: echo env
      run: running from prd environment
