name : Three environemnt setup
on : workflow_dispatch

jobs:
  
  DevJob:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: echo env
      run: echo running from dev environment

  QaJob:
      runs-on: ubuntu-latest
      environment: Qa
      needs: DevJob
      steps:
      - name: echo env
        run: echo running from qa environment
      
      
  PrdJob:
      runs-on: ubuntu-latest
      environment: Prd
      needs: QaJob
      steps:
        - name: echo env
          run: echo running from prd environement
