name : Three environemnt setup
on : workflow_dispatch

jobs:
  
  DevJob:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - name: echo env
      run: echo running from ${{ vars.DEV_ENV }} with secret ${{ secrets.ENV }} environment

  QaJob:
      runs-on: ubuntu-latest
      environment: Qa
      needs: DevJob
      steps:
      - name: echo env
        run: echo running from ${{ vars.QA_ENV }} with secret ${{ secrets.ENV }} environment
      
      
  PrdJob:
      runs-on: ubuntu-latest
      environment: Prd
      needs: QaJob
      steps:
        - name: echo env
          run: echo running from ${{ vars.PRD_ENV }} with secret ${{ secrets.ENV }} environement
